---
- name: Install and configure firewalld on RHEL
  hosts: all  # This will be overridden by the AAP inventory
  become: true # Use privilege escalation (sudo) to run the tasks

  tasks:

    - name: Ensure sudo and Python are installed (RHEL)
      ansible.builtin.raw: sudo dnf -y install sudo python3
      args:
        creates: /usr/bin/python3
      when: ansible_os_family == "RedHat"

    - name: Ensure firewalld is installed (RHEL)
      ansible.builtin.dnf:
        name: firewalld
        state: present

    - name: Ensure firewalld service is running and enabled (RHEL)
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true

    - name: Configure firewalld
      ansible.posix.firewalld:
        service: "{{ item }}"
        permanent: true
        state: enabled
        immediate: true
      loop:
        - http
        - https

    - name: Restart the firewalld service
      ansible.builtin.service:
        name: firewalld
        state: restarted
        enabled: true
