---
- name: Destroy aws resources using Terraform Cloud
  hosts: all
  gather_facts: false
  tasks:
  - name: Create a destroy run to remove resources
    hashicorp.terraform.run:
      tf_hostname: "{{ tf_hostname }}"
      tf_validate_certs: false
      tf_token: "{{ tf_token }}"
      organization: "{{ tf_org }}"
      workspace: "{{ tf_workspace }}"
      run_message: "Destroy run to remove resources by Ansible"
      is_destroy: true
      auto_apply: true
      poll_interval: 5
      poll_timeout: 360
      state: "present"
