---
- name: Destroy aws resources using Terraform Cloud
  hosts: all
  gather_facts: false
  tasks:
  - name: Create a destroy run to remove resources
    hashicorp.terraform.run:
      tf_token: "{{ tfcloud_token }}"
      organization: "{{ tfcloud_org }}"
      workspace: "{{ tfcloud_workspace }}"
      run_message: "Destroy run to remove resources by Ansible"
      is_destroy: true
      auto_apply: true
      poll_interval: 5
      poll_timeout: 360
      state: "present"
